### PR TITLE
Landlord see own listings

### PR DESCRIPTION
**Pull request by qf2050**

### CODE REVIEW

**Comment by maludee** [comment]
I see the landlord's own listings are populating correctly but can you adjust so that this follows these requirements from the ticket:

> Landlord homepage should look the same as the user's homepage, but just show that landlord's own listings
> It should have the same header/navigation bar as the user's homepage except:
> There will be a "create new listing button" on this page either on the header or somewhere easy to find

In case you need a reference for what the user's page looks like, it looks like this: http://127.0.0.1:8000/rentalspage/?borough=Brooklyn (login as user to see). So the landlord's page with his own listings should look like that, but just be limited to his own listings. 

Is this PR also intended to cover the work for https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/issues/73? If so, it looks like there is no place for the landlord to upload photos.

**Comment by qf2050** [comment]
I try to upload the I use the boto3 to upload image but get "Unable to locate credentials" @maludee  have you meet same problem?

**Comment by maludee** [comment]
> I try to upload the I use the boto3 to upload image but get "Unable to locate credentials" @maludee have you meet same problem?

@qf2050 I have not used boto3 for anything, so not sure about this error. check with @SiriErrabelli maybe?

**Review by maludee — CHANGES_REQUESTED** [review]
Looking better so far! 

couple of things to change before merging:
- looks like the images are not coming through on the landlord page
- each listing is taking up the whole screen 
- looks like test coverage went down - we are supposed to keep it above 85% so could you also add a test case or two to make sure the coverage stays up? it might have gone down because one was commented out in this PR 
- the create new listing button on the bottom of the page doesn't do anything, not sure if that was on purpose (is it going to be part of a separate PR)? 
- If I click on "RentwiseNYC" on the navbar, it tries to take me to the user homepage which the landlord doesn't have permission for 

Sorry it is a lot, if you want to get on a call with the team to discuss any of the changes let me know!

**Comment by qf2050** [comment]
@SiriErrabelli Have you seen the error"
Exception Type: | NoCredentialsError
Unable to locate credentials"
It prevents me from uploading images

**Comment by qf2050** [comment]
@maludee  The other functions are done  expect the image loading, I can not upload image in my Local Django, is it necessary to add os env "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY"?

**Comment by maludee** [comment]
> @maludee The other functions are done expect the image loading, I can not upload image in my Local Django, is it necessary to add os env "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY"?

@qf2050 yes you need to have all the environment variables on your local as well in order to test. Check out the whatsapp group for the values in case you don't have them. 

Since you requested review I see that the formatting was fixed (the listings no longer take up the whole 100% width) but I don't see that the other parts I mentioned earlier (the navbar, the create new listings button, the testing coverage, etc) have been updated. Can you explain whether this is supposed to be part of this PR, or are you planning to fix those as part of separate PR/ticket?

**Comment by qf2050** [comment]
@maludee  I am planning to fix those as part of separate PR

**Comment by qf2050** [comment]
@maludee  the create new listings butoon,It looks like it can be used, can't you click the button or other?

**Comment by maludee** [comment]
> @maludee the create new listings butoon,It looks like it can be used, can't you click the button or other?

@qf2050 no nothing happens when I click the button

**Comment by qf2050** [comment]
@maludee  I click the button and can add the rental.maybe you can zoom in and zoom out the web

**Comment by maludee** [comment]
@aru456 @vamshinaik309 @SiriErrabelli can one of you review this PR and test out the functionality? It doesn't seem to be working for me but might be something I am doing wrong

**Comment by qf2050** [comment]
[轻录屏-2024-04-07-00-32-57.webm](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/assets/104478323/646fb9b1-4ff4-4d4f-8aa4-64bb71fd5b39)
@maludee this video is right?  Or I Misunderstood your meaning.

**Review by SiriErrabelli — CHANGES_REQUESTED** [review]
Hey @qf2050 , I have reviewed your pull request, I think some chan ges are required in landlord functionality before we can merge this request

- Remove the link column from the form(it's not required)
- Unit type has to be a dropdown(with values from table)
- Neighbourhood should be a dropdown(with values from table)
- there is no zipcode column(it is required)
- there is no upload to upload multiple images( am i missing something?)
- There is no validation for availability date(should not take past dates)
- when i Signed up and signed in it let me in without admin approval(verified was false in the table, this should not happen) - we did this functionality before.
- preferably make number of rooms, bedrooms, bathrooms dropdown(1,1.5.2..)
- There has to be a borough column(dropdown)
- There has to be a broker fee column
- Fav button should not be shown on listing
- listing is not opening(i think this is a seperate PR right?)
- listing high level doesn't show as many details as user page
- when i go to postlisting page, i should be able to see the header/Navbar

**Review by SiriErrabelli — COMMENTED** [review]
landlord validation is working
a lot more info showing
listings are opening
drop downs are good

broker fee has to take a value
when i put availability date the page breaks and is showing an error
With any value i am not able to submit the form, it shows an error

**Review by SiriErrabelli — CHANGES_REQUESTED** [review]
Hi @qf2050, I have gone through your changes. Most of it looks good, except for these:

- the listing images are not showing
- even though i passed the map env variable, the map is not loading( i put a real address) and therefore nearby metro stations are not loading(this might be because there are no lat/long values, we can leave this for later)
- search functionality is not working(it's not mandatory, better to remove the bar if not planning on completing functionality)
- total number of rooms shouldn't be less than number of bedrooms(?)

**Review by SiriErrabelli — COMMENTED** [review]
Hi @qf2050, i have checked your PR
i'm still not able to see images, all the images for the listings are in users_rentalimages with id as listing id and multiple image links in multiple rows. Whenever i post a new listing, I don't see any links being added to that table.

**Review by SiriErrabelli — CHANGES_REQUESTED** [review]
Hi @qf2050 , i have checked your PR, but now i am unable to post any listing,
the following error is showing up:
ModuleNotFoundError at /post_new_listings/
[ModuleNotFoundError at _post_new_listings_.pdf](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/files/14971862/ModuleNotFoundError.at._post_new_listings_.pdf)

**Pull request merged**
