### PR TITLE
User SignUp

### PR DESCRIPTION
**Pull request by qf2050**
User SignUp

### CODE REVIEW

**Comment by qf2050** [comment]
this pr resolve #32

**Review by maludee — CHANGES_REQUESTED** [review]
- tried to sign up for an account and got an error "IntegrityError at /signup/user_up - @qf2050 was this working for you when you tested it? 
- can you also make sure to use the django form templates we picked in standup? 
cc @aru456

**Comment by maludee** [comment]
@qf2050 talked to @aru456 and it looks like it's just broken because you have to pull from the develop branch again - some fields were changed in the database. @aru456 will merge his PR - then you pull from develop - test this again, and after that I think it should work

**Comment by qf2050** [comment]
So I should wait @aru456  to update the develop branch and then change the code?

**Comment by qf2050** [comment]
So I should wait @aru456 to update the develop branch and then fix the code?

**Comment by maludee** [comment]
> So I should wait @aru456 to update the develop branch and then fix the code?

yep @qf2050 I think that sounds like a good plan

**Comment by qf2050** [comment]
@aru456  I want to know  where are django form templates,It seems that no form file in the project.

**Comment by aru456** [comment]
https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/tree/aravind-03.05

@qf2050 check the above branch for reference, you can see landlord/signup folder in templates and forms.py for django form templates.

also i’ve merged the changes of model and now you need to pull changes from develop branch inorder to make you code work.

**Comment by qf2050** [comment]
@aru456  ok thank you!

**Review by maludee — APPROVED** [review]

**Pull request merged**
