### PR TITLE
Qf2050#127 and #132

### PR DESCRIPTION
**Pull request by qf2050**

### CODE REVIEW

**Review by maludee — CHANGES_REQUESTED** [review]
- @qf2050 ticket #127 is asking to make it so that you can click on the entire card to open a listing from the favorites page. In other words, look at the way it is on the main rental browse page and replicate that on the favorites page. 

Here's the quote from the bug ticket that should be fixed:

> the listing card doesn't have a hyperlink to view the listing details, instead the thumbnail image has which is different from the general rentals page.

- Shadow on the favorites heart looks good now, so this fixes #132. 

- Why are there changes to the `landlord_homepage.html` file? I don't think this should be included in this PR?

**Comment by qf2050** [comment]
@maludee  I have delete the change in `landlord_homepage.html` and the click

**Review by maludee — CHANGES_REQUESTED** [review]
now getting an error when i click on favorites 
Screen Shot 2024-04-22 at 2 32 11 PM

**Comment by maludee** [comment]
@qf2050 the formatting looks off on the favorites page now - the text is not filling the whole box and the image is not filling the whole card. 

Can you look at the formatting on the favorites page on dev: http://rent-wise-env.eba-3qbiyspq.us-east-1.elasticbeanstalk.com/favorites/ or http://rent-wise-env.eba-3qbiyspq.us-east-1.elasticbeanstalk.com/rentalspage/?borough=All%28NYC%29&min_price=&max_price= 
and please copy the formatting? your favorites page should look exactly the same, but the entire card should be clickable like it is on the main listings page.

**Review by maludee — CHANGES_REQUESTED** [review]
@qf2050 looks like the favorites card clicking issue was fixed by @aru456 in a recent PR, so for this one you can take out everything except for the favorites heart outline - once that's done we can merge this PR

**Review by maludee — APPROVED** [review]

**Pull request merged**
