### PR TITLE
Modified the search functionality and adjsuted the CSS bug

### PR DESCRIPTION
**Pull request by aru456**
I've modified the search functionality and adjusted the CSS bug that's haunting me. Also I made the header fixed in all pages and modified the placeholder page to redirect to homepage.

### CODE REVIEW

**Review by maludee — CHANGES_REQUESTED** [review]
Think these are possible to fix in this PR? 
- it doesn't let me search for all listings anymore, is this on purpose? eg, if I leave the "search for a rental listing" field blank, it forces me to enter a value
- I think you could update the wording  to "Search by borough or neighborhood" because for example I searched for "NYC" and it gave me no results, so I think it should be clear to the user that this is only a borough / neighborhood search.
 
These are potential smaller bugs but not necessarily needed in this PR
- There is some weird behavior like if I type "All" it shows me one listing in manhattan (why?? I have no idea) 
- If I type "Manhattan " with a space, it also shows me that same listing. 

Everything else looks really good to me, background looks great and the filters and everything seem to be working perfectly now

**Comment by aru456** [comment]
it doesn't let me search for all listings anymore, is this on purpose? eg, if I leave the "search for a rental listing" field blank, it forces me to enter a value

this is on purpose, a user will not usually search the whole NYC right, it will give him a lot of listings he can't handle, also we are not giving any filter for borough or location, so only if he inputs borough or neighborhood, then he will see all the listings that match either the borough or the neighborhood


- Changed the wording "Search listing by Borough/Neighborhood"
- Fyi included the All(NYC) option
- All matched with "Manhattan Alley" so it gave the result for you but not anymore 
- Search was previously "contains" 'Manhattan ', so you got that 'Manhattan Valley' result again as it is contains
- Now it is only a perfect match in the backend db with the value you put in search bar
-The frontend dropdown is now "contains" which means it will match with %word%

**Review by maludee — APPROVED** [review]

**Comment by maludee** [comment]
looks good, one thing to note is that the search is case sensitive so if someone just types "manhattan" and hits enter they will get no listings

**Comment by aru456** [comment]
@maludee Restrcited the user search button if he does not select any option in the drop-down. 
Only the serchbutton is enabled when he selects any dropdown value

**Pull request merged**
